### ISSUE TITLE
Test run failed: Instrumentation run failed due to 'java.lang.ClassNotFoundException'

### ISSUE THREAD

**Issue by rainy1216** [baidu/Cafe#26]
运行时出现Test run failed: Instrumentation run failed due to 'java.lang.ClassNotFoundException'这个问题

**Comment by rainy1216** [comment]
但是又不知道是指那个Class

**Comment by luxiaoyu** [comment]
是不是cafe.jar没有放到libs下面

**Comment by rainy1216** [comment]
TestApiDemos运行的时候这里都是空指针

------------------ 原始邮件 ------------------
发件人: "keymath";notifications@github.com;
发送时间: 2014年1月14日(星期二) 上午9:39
收件人: "BaiduQA/Cafe"Cafe@noreply.github.com; 
抄送: "Rainy"1171789187@qq.com; 
主题: Re: [Cafe] Test run failed: Instrumentation run failed due to'java.lang.ClassNotFoundException' (#26)

是不是cafe.jar没有放到libs下面

**Comment by luxiaoyu** [comment]
求助要帖错误信息，否则别人无法帮助你

**Comment by rainy1216** [comment]
你看边看不到图片么？
// 点击HOME键
        remote.pressKey(KeyEvent.KEYCODE_HOME);
        // 点击锁屏键
        remote.pressKey(KeyEvent.KEYCODE_POWER);
        // 点击音量键
        remote.pressKey(KeyEvent.KEYCODE_VOLUME_DOWN);
        // 点击菜单键
        remote.pressKey(KeyEvent.KEYCODE_MENU);
        // 点击返回键
        remote.pressKey(KeyEvent.KEYCODE_BACK);
        // 点击搜索键
        remote.pressKey(KeyEvent.KEYCODE_SEARCH);
        // 卸载sd卡
        remote.unmount();
        // 安装sd卡
        remote.mount();

这些都是空指针

**Comment by luxiaoyu** [comment]
哦，你这样说我就明白了，你没有安装Café.apk啊，还有跑case前需要运行café_setup.bat

谢谢
鲁晓宇

发件人: rainy1216 [mailto:notifications@github.com]
发送时间: 2014年1月14日 10:01
收件人: BaiduQA/Cafe
抄送: Lu,Xiaoyu(Mobile Application RD)
主题: Re: [Cafe] Test run failed: Instrumentation run failed due to 'java.lang.ClassNotFoundException' (#26)

你看边看不到图片么？
// 点击HOME键
remote.pressKey(KeyEvent.KEYCODE_HOME);
// 点击锁屏键
remote.pressKey(KeyEvent.KEYCODE_POWER);
// 点击音量键
remote.pressKey(KeyEvent.KEYCODE_VOLUME_DOWN);
// 点击菜单键
remote.pressKey(KeyEvent.KEYCODE_MENU);
// 点击返回键
remote.pressKey(KeyEvent.KEYCODE_BACK);
// 点击搜索键
remote.pressKey(KeyEvent.KEYCODE_SEARCH);
// 卸载sd卡
remote.unmount();
// 安装sd卡
remote.mount();

这些都是空指针

**Comment by VorbeiYu** [comment]
你好，我也遇到这个问题，我是自己写了个空的应用，然后自己写了个很简单的testcase，就一直提示这个错误。你们说的运行apk，在手机上运行吗还是在电脑上啊

**Comment by VorbeiYu** [comment]
我自己写的helloworld的class需要打包成jar包吗
